apiVersion: v1
kind: Service
metadata:
  name: web-deployment-service
  labels:
    app: web-deployment
spec:
  type: ClusterIP 
  selector:
    app: web-deployment 
  ports:
    - port: 80
      targetPort: 80
