apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: inspect
  name: inspect
spec:
  containers:
  - image: nginx
    name: inspect
    resources: {}
    env:
    - name: USERNAME
      value: "demo-admin"
    - name: PASSWORD
      value: "demo-password"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
